-- Varias tiendas en el mismo proyecto de Supabase.
-- Cada cliente tiene su tienda y solo ve y edita lo suyo.
--
-- ORDEN: 1) schema.sql (ya ejecutado)  2) panel.sql del panel de clientes  3) este archivo.
-- Supabase > SQL Editor > New query > pegar todo este archivo > Run.
-- Se puede ejecutar más de una vez sin dañar nada.
-- La tienda que ya tienes pasa a ser la tienda número 1, con todos sus productos,
-- categorías, logo, celular y administradores. No se borra nada.

do $$
begin
  if to_regprocedure('public.es_admin_panel()') is null then
    raise exception 'Primero ejecuta panel.sql (del panel de clientes) y después este archivo.';
  end if;
end;
$$;

-- Tiendas -------------------------------------------------------------------
create table if not exists public.tiendas (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]([a-z0-9-]{0,38}[a-z0-9])?$'),
  nombre_tienda text not null default 'Mi tienda' check (char_length(nombre_tienda) between 1 and 60),
  logo_url text,
  logo_path text,
  codigo_pais text not null default '504' check (codigo_pais ~ '^[0-9]{1,4}$'),
  celular text not null default '' check (celular ~ '^[0-9]{0,14}$'),
  dominio text unique check (dominio is null or dominio ~ '^[a-z0-9.-]{3,120}$'),
  activa boolean not null default true,
  nombre_plan text not null default '' check (char_length(nombre_plan) <= 40),
  limite_productos integer not null default 2000 check (limite_productos > 0),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

-- La tienda actual pasa a ser la tienda 1 (con los datos de "configuracion")
insert into public.tiendas (id, slug, nombre_tienda, logo_url, logo_path, codigo_pais, celular, nombre_plan, limite_productos)
select 1, 'ferreteria', c.nombre_tienda, c.logo_url, c.logo_path, c.codigo_pais, c.celular, 'Premium', 50000
from public.configuracion c where c.id = 1
on conflict (id) do nothing;

insert into public.tiendas (id, slug, nombre_tienda, nombre_plan, limite_productos)
values (1, 'ferreteria', 'Ferretería', 'Premium', 50000)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('public.tiendas', 'id'),
              greatest((select max(id) from public.tiendas), 1));

-- Dueños de cada tienda (quién puede entrar al panel de esa tienda) ---------
create table if not exists public.tienda_admins (
  tienda_id bigint not null references public.tiendas (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  primary key (tienda_id, user_id)
);

create index if not exists tienda_admins_user_id_idx on public.tienda_admins (user_id);

-- Los administradores que ya tenías quedan como dueños de la tienda 1
insert into public.tienda_admins (tienda_id, user_id)
select 1, user_id from public.administradores
on conflict do nothing;

-- Enlace entre el cliente del panel y su tienda
alter table public.clientes add column if not exists tienda_id bigint
  references public.tiendas (id) on delete set null;
create unique index if not exists clientes_tienda_id_idx on public.clientes (tienda_id) where tienda_id is not null;

-- Funciones de permisos ------------------------------------------------------
-- Tiendas que el usuario actual puede administrar (todas si es administrador del panel).
create or replace function public.tiendas_administradas()
returns setof bigint
language sql
stable
security definer
set search_path = ''
as $$
  select t.id from public.tiendas t where (select public.es_admin_panel())
  union
  select a.tienda_id from public.tienda_admins a where a.user_id = (select auth.uid());
$$;

-- Tiendas cuyo catálogo se puede ver: las activas, más las propias aunque estén suspendidas.
create or replace function public.tiendas_visibles()
returns setof bigint
language sql
stable
security definer
set search_path = ''
as $$
  select t.id from public.tiendas t where t.activa
  union
  select public.tiendas_administradas();
$$;

create or replace function public.es_admin_tienda(t bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select t in (select public.tiendas_administradas());
$$;

-- Tienda a la que pertenece una imagen: "5/abc.webp" es de la tienda 5.
-- Las imágenes que ya existían (sin número al inicio) son de la tienda 1.
create or replace function public.tienda_de_ruta(ruta text)
returns bigint
language sql
immutable
set search_path = ''
as $$
  select case when split_part(ruta, '/', 1) ~ '^[0-9]{1,18}$'
              then split_part(ruta, '/', 1)::bigint else 1 end;
$$;

revoke execute on function public.tiendas_administradas() from public;
revoke execute on function public.tiendas_visibles() from public;
revoke execute on function public.es_admin_tienda(bigint) from public;
grant execute on function public.tiendas_administradas() to anon, authenticated;
grant execute on function public.tiendas_visibles() to anon, authenticated;
grant execute on function public.es_admin_tienda(bigint) to anon, authenticated;
grant execute on function public.tienda_de_ruta(text) to anon, authenticated;

-- Categorías y productos llevan la tienda ------------------------------------
alter table public.categorias add column if not exists tienda_id bigint references public.tiendas (id) on delete cascade;
alter table public.productos add column if not exists tienda_id bigint references public.tiendas (id) on delete cascade;
update public.categorias set tienda_id = 1 where tienda_id is null;
update public.productos set tienda_id = 1 where tienda_id is null;
alter table public.categorias alter column tienda_id set not null;
alter table public.productos alter column tienda_id set not null;

-- El nombre de categoría ya no es único en todo el proyecto, sino dentro de cada tienda
alter table public.categorias drop constraint if exists categorias_nombre_key;
create unique index if not exists categorias_tienda_nombre_idx on public.categorias (tienda_id, nombre);
create unique index if not exists categorias_id_tienda_idx on public.categorias (id, tienda_id);

-- Un producto solo puede usar categorías de su misma tienda
alter table public.productos drop constraint if exists productos_categoria_id_fkey;
alter table public.productos drop constraint if exists productos_categoria_tienda_fkey;
alter table public.productos add constraint productos_categoria_tienda_fkey
  foreign key (categoria_id, tienda_id) references public.categorias (id, tienda_id)
  on delete set null (categoria_id);

create index if not exists productos_tienda_creado_idx on public.productos (tienda_id, creado_en desc);
create index if not exists categorias_tienda_id_idx on public.categorias (tienda_id);

-- Límite de productos según el plan, y no se puede mover nada a otra tienda --
create or replace function public.revisar_tienda_productos()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  lim integer;
  plan text;
  total integer;
begin
  if tg_op = 'UPDATE' then
    if new.tienda_id <> old.tienda_id then
      raise exception 'Un producto no se puede pasar a otra tienda.' using errcode = 'P0001';
    end if;
    return new;
  end if;

  select limite_productos, nombre_plan into lim, plan from public.tiendas where id = new.tienda_id;
  perform pg_advisory_xact_lock(hashtext('public.productos.limite'), new.tienda_id::integer);
  select count(*) into total from public.productos where tienda_id = new.tienda_id;
  if total >= lim then
    raise exception 'Llegaste al límite de % productos de tu plan%. Para agregar más, pide un cambio de plan.',
      lim, case when plan <> '' then ' ' || plan else '' end
      using errcode = 'P0001';
  end if;
  return new;
end;
$$;

-- Quita el límite antiguo de una sola tienda, si se llegó a instalar
drop trigger if exists limite_productos on public.productos;
drop trigger if exists tienda_productos on public.productos;
create trigger tienda_productos before insert or update of tienda_id on public.productos
  for each row execute function public.revisar_tienda_productos();

create or replace function public.fijar_tienda_categoria()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.tienda_id <> old.tienda_id then
    raise exception 'Una categoría no se puede pasar a otra tienda.' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

drop trigger if exists tienda_categorias on public.categorias;
create trigger tienda_categorias before update of tienda_id on public.categorias
  for each row execute function public.fijar_tienda_categoria();

-- Seguridad por filas (RLS) -------------------------------------------------
alter table public.tiendas enable row level security;
alter table public.tienda_admins enable row level security;

-- Datos públicos de las tiendas (nombre, logo, celular, si está activa)
drop policy if exists "tiendas publicas" on public.tiendas;
create policy "tiendas publicas" on public.tiendas
  for select to anon, authenticated using (true);

-- El dueño solo cambia nombre, logo y celular; el plan, límite, dirección,
-- dominio y si está activa solo se cambian desde el panel de clientes.
revoke insert, update, delete on public.tiendas from anon, authenticated;
grant update (nombre_tienda, logo_url, logo_path, codigo_pais, celular, actualizado_en)
  on public.tiendas to authenticated;

drop policy if exists "dueno edita tienda" on public.tiendas;
create policy "dueno edita tienda" on public.tiendas
  for update to authenticated
  using (id in (select public.tiendas_administradas()))
  with check (id in (select public.tiendas_administradas()));

drop policy if exists "ver propias tiendas" on public.tienda_admins;
create policy "ver propias tiendas" on public.tienda_admins
  for select to authenticated using (user_id = (select auth.uid()) or (select public.es_admin_panel()));
revoke insert, update, delete on public.tienda_admins from anon, authenticated;

-- Catálogo: se ve el de las tiendas activas
drop policy if exists "catalogo publico categorias" on public.categorias;
create policy "catalogo publico categorias" on public.categorias
  for select to anon, authenticated using (tienda_id in (select public.tiendas_visibles()));

drop policy if exists "catalogo publico productos" on public.productos;
create policy "catalogo publico productos" on public.productos
  for select to anon, authenticated using (tienda_id in (select public.tiendas_visibles()));

-- Cada dueño modifica solo su tienda
drop policy if exists "admin gestiona categorias" on public.categorias;
create policy "admin gestiona categorias" on public.categorias
  for all to authenticated
  using (tienda_id in (select public.tiendas_administradas()))
  with check (tienda_id in (select public.tiendas_administradas()));

drop policy if exists "admin gestiona productos" on public.productos;
create policy "admin gestiona productos" on public.productos
  for all to authenticated
  using (tienda_id in (select public.tiendas_administradas()))
  with check (tienda_id in (select public.tiendas_administradas()));

-- La tabla "configuracion" queda como copia de respaldo; ya no se edita.
drop policy if exists "admin edita configuracion" on public.configuracion;

-- Imágenes: cada tienda sube y borra solo en su carpeta ("5/...") -------------
drop policy if exists "admin sube imagenes" on storage.objects;
create policy "admin sube imagenes" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'productos'
              and public.tienda_de_ruta(name) in (select public.tiendas_administradas()));

drop policy if exists "admin actualiza imagenes" on storage.objects;
create policy "admin actualiza imagenes" on storage.objects
  for update to authenticated
  using (bucket_id = 'productos'
         and public.tienda_de_ruta(name) in (select public.tiendas_administradas()));

drop policy if exists "admin borra imagenes" on storage.objects;
create policy "admin borra imagenes" on storage.objects
  for delete to authenticated
  using (bucket_id = 'productos'
         and public.tienda_de_ruta(name) in (select public.tiendas_administradas()));

drop policy if exists "admin ve imagenes" on storage.objects;
create policy "admin ve imagenes" on storage.objects
  for select to authenticated
  using (bucket_id = 'productos'
         and public.tienda_de_ruta(name) in (select public.tiendas_administradas()));
